# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 9add498200556502c47bf3d925d882455911fbea2794c0d56788c92e041d2b31aec5451abb9970d066561c6822e49a0e7600ee25bcd26a54772009cce3efd6f5

test:
  secret_key_base: dfb1fbd288cdc35fd0080a1b0d7a2701f6b5780146f3608142a383b61cb654d78cbc962705edb6fa2b39f3fe074cf1ace50e6ded2c79e4f7af2ed5c084c9ee02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
